# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

server:
  port: 4000
  compress: true
  header: true

# Site
title: Bluelich's Blog
subtitle: namespace bluelich
description: iOS开发者,macOS开发者
keywords:
author: Bluelich
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://bluelich.com
root: /
permalink: :year/:month/:day/:subtitle/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

index_generator:
  path: ''
  per_page: 5
  order_by: -date
  
archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

# Category & Tag
default_category: Other
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

social:

  Weibo: http://weibo.com/u/1376767097
  GitHub: http://github.com/bluelich
  Facebook: https://www.facebook.com/bluelich
  Twitter: https://twitter.com/hnjyzqq
  Gmail: mailto:bluelich@gmail.com
  Q Mail: mailto:bluelich@qq.com

since: 2016

creative_commons: zero

menu:

  home: /

  categories: /categories

  archives: /archives

  tags: /tags

scheme: Pisces

google_analytics: UA-78250446-1
baidu_analytics: 6e13fff54d99ee837b32c9e5e8203eaa
tencent_analytics: 60661416

duoshuo_hotartical: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
